# example values

indexing-settings:
  sites:
    - url: https://lenta.ru/
      name: Лента.ру
    - url: https://skillbox.ru/
      name: Skillbox
    - url: https://www.playback.ru/
      name: PlayBack.Ru

server:
  port: 8080

spring:
  datasource:
    username: root
    password: Cfkk161205
    url: jdbc:mysql://localhost:3306/
      search_engine?useSSL=false
      &requireSSL=false
      &allowPublicKeyRetrieval=true&characterEncoding=utf8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

connect-settings:
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com